name: Test Action  # Name of the workflow

on:  # Defines when this action should run
  push:  # Trigger on push events
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  test:  # Job name
    runs-on: ubuntu-latest  # The job will run on an Ubuntu machine
    steps:
      - name: Checkout code  # Step 1: Get the latest code
        uses: actions/checkout@v3

      - name: 22f3001831@ds.study.iitm.ac.in  # Step 2: Example task
        run: echo "Hello, world!"
